### Login de usuario
POST localhost:8080/api/auth/login
Content-Type: application/json

{ "username":  "user@superstore.com", "password": "password" }

> {%
    client.global.set("customer_id", response.body.id);
%}

### Devuelve la información que exista del usuario
GET localhost:8080/api/customers/{{customer_id}}

### Crea un nuevo pedido (order) para el usuario
POST localhost:8080/api/customers/{{customer_id}}/orders
Content-Type: application/json

{
  "id": "{{$random.uuid}}",
  "address": "carrer de muntaner 137, 2-1",
  "postalCode": "08099",
  "city": "Barcelona",
  "country": "Spain"
}

> {%
    client.global.set("order_id", response.body.id);
%}

### Obtiene el id de un producto cualquiera
GET localhost:8080/api/products

> {%
    client.global.set("product_id", response.body[0].id);
%}

### Añade el producto al pedido
POST localhost:8080/api/orders/{{order_id}}/products?productId={{product_id}}

### devuelve los pedidos que existen para el usuario
GET localhost:8080/api/customers/{{customer_id}}/orders
